# Generated by Django 4.2.1 on 2023-11-16 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.CharField(max_length=255)),
                ('token_name', models.CharField(max_length=255)),
                ('token_symbol', models.CharField(max_length=10)),
                ('token_decimal', models.IntegerField()),
                ('last_checked_price_usd', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('last_checked_price_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('amount_spent_for_purchases_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('last_calculated_balance_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('last_calculated_balance_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTokenBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=10, max_digits=19)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.token')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('hash', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=10, max_digits=19)),
                ('gas_price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('gas_used', models.DecimalField(decimal_places=10, max_digits=19)),
                ('function_name', models.CharField(max_length=255)),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_from', to='wallet.wallet')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_to', to='wallet.wallet')),
                ('token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.token')),
            ],
        ),
    ]
