# Generated by Django 4.2.1 on 2023-11-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_being_calculated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
