# Generated by Django 4.2.1 on 2024-01-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_transaction_from_wallet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalETHPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=32)),
            ],
        ),
        migrations.AddField(
            model_name='token',
            name='last_checked_usd_price_decimal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='last_checked_price_usd',
            field=models.IntegerField(null=True),
        ),
    ]
