# Generated by Django 4.2.1 on 2024-01-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_historicalethprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='last_checked_price_usd',
            field=models.BigIntegerField(null=True),
        ),
    ]
