# Generated by Django 4.2.1 on 2024-01-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_token_last_checked_price_usd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='last_checked_usd_price_decimal',
        ),
        migrations.AlterField(
            model_name='token',
            name='last_checked_price_usd',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
