# Generated by Django 4.2.1 on 2024-01-25 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_remove_token_last_checked_usd_price_decimal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='contract',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='received_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_token', to='wallet.token', to_field='contract'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='related_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_wallet', to='wallet.wallet', to_field='address'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sent_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_token', to='wallet.token', to_field='contract'),
        ),
    ]
