# Generated by Django 4.2.1 on 2024-01-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_alter_transaction_block_alter_transaction_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='received_amount',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sent_amount',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
