# Generated by Django 4.2.1 on 2024-01-25 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_alter_transaction_received_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='received_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_token', to='wallet.token'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sent_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_token', to='wallet.token'),
        ),
    ]
