# Generated by Django 4.2.1 on 2024-01-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_alter_transaction_received_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='hash',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
