# Generated by Django 4.2.1 on 2024-01-27 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_alter_transaction_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeTransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchanged_token_amount', models.CharField(max_length=128)),
                ('is_receiver', models.BooleanField(null=True)),
                ('denominated_in', models.CharField(max_length=64, null=True)),
                ('price_in_denominated_token', models.CharField(max_length=128, null=True)),
                ('price_in_usd', models.CharField(max_length=128, null=True)),
                ('value_of_trade_in_denominated_token', models.CharField(max_length=128, null=True)),
                ('value_of_trade_in_usd', models.CharField(max_length=128, null=True)),
                ('exchanged_token', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wallet.token', to_field='contract')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.transaction', to_field='hash')),
            ],
        ),
    ]
