# Generated by Django 4.2.1 on 2024-01-27 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_tradetransactiondetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradetransactiondetails',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.transaction', to_field='hash', unique=True),
        ),
    ]
