# Generated by Django 4.2.1 on 2024-01-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0017_alter_tradetransactiondetails_exchanged_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='amount_received_from_selling',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='wallettokenbalance',
            name='purchased_token_amount',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallettokenbalance',
            name='sold_token_amount',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallettokenbalance',
            name='token_realized_p_l',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallettokenbalance',
            name='token_total_p_l',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallettokenbalance',
            name='token_unrealized_p_l',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallettokenbalance',
            name='total_usd_received_from_selling',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallettokenbalance',
            name='total_usd_spent_for_token',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=64),
            preserve_default=False,
        ),
    ]
