# Generated by Django 4.2.1 on 2024-01-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0018_wallet_amount_received_from_selling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettokenbalance',
            name='average_purchase_price',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='wallettokenbalance',
            name='balance',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AlterField(
            model_name='wallettokenbalance',
            name='net_purchase_price',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='wallettokenbalance',
            unique_together={('wallet', 'token')},
        ),
    ]
