# Generated by Django 4.2.1 on 2024-02-19 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0019_alter_wallettokenbalance_average_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradetransactiondetails',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade_details', to='wallet.transaction', to_field='hash'),
        ),
    ]
