# Generated by Django 4.2.1 on 2024-02-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0020_alter_tradetransactiondetails_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type_of_transaction',
            field=models.CharField(choices=[('TRADE', 'Trade'), ('SEND', 'Send'), ('RECEIVE', 'Receive'), ('APPROVE', 'Approve')], default=True, max_length=64, null=True),
        ),
    ]
