# Generated by Django 4.2.1 on 2024-03-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0021_transaction_type_of_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_realized_p_l',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_total_p_l',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_unrealized_p_l',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
