# Generated by Django 4.2.1 on 2024-03-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0023_alter_wallet_wallet_realized_p_l_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='last_calculated_balance_timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
