# Generated by Django 4.2.1 on 2024-03-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0024_alter_wallet_last_calculated_balance_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettokenbalance',
            name='last_calculated_balance_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=64),
        ),
    ]
