# Generated by Django 4.2.1 on 2024-04-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0025_wallettokenbalance_last_calculated_balance_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='token_image_url',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
