# Generated by Django 4.2.1 on 2024-04-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0026_token_token_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type_of_transaction',
            field=models.CharField(choices=[('TRADE', 'Trade'), ('SEND', 'Send'), ('RECEIVE', 'Receive'), ('APPROVE', 'Approve')], default='Trade', max_length=64, null=True),
        ),
    ]
