# Generated by Django 4.2.1 on 2024-06-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0030_alter_wallettokenbalance_average_purchase_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
