# Generated by Django 4.2.1 on 2024-06-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0031_suspicioustokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalethprice',
            name='timestamp',
            field=models.IntegerField(unique=True),
        ),
    ]
